# Go cross compiler (xgo): Wildcard layer to the latest 1.3 release
# Copyright (c) 2014 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM xwl7001/xgo-1.3.3

MAINTAINER Péter Szilágyi <peterke@gmail.com>
