# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM xwl7001/xgo-1.9.x

MAINTAINER Péter Szilágyi <peterke@gmail.com>
