# Go cross compiler (xgo): Wildcard layer to the latest 1.6 release
# Copyright (c) 2016 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM xwl7001/xgo-1.6.3

MAINTAINER Péter Szilágyi <peterke@gmail.com>
